version: '3'

services:
  db:
    image: postgres:9-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - staticfiles:/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sheru
    ports:
      - "8080:80"

  sheru:
    build: .
    restart: always
    expose:
      - "8000"
    volumes:
      - staticfiles:/project/static
      - /var/run/docker.sock:/var/run/docker.sock
      - ./project/sheru/migrations:/project/sheru/migrations
    depends_on:
      - db
    environment: 
      DB_USER: "${POSTGRES_USER}"
      DB_PWD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${POSTGRES_DB}"
      DEBUG: "${DEBUG}"
      HEADER_AUTH: "True"

volumes:
  staticfiles:
  pgdata: