version: '3'

services:
  db:
    image: postgres:9-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - staticfiles:/static:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sheru-daphne
    ports:
      - "8080:80"

  sheru-daphne:
    build: .
    restart: always
    expose:
      - "8000"
    volumes:
      - staticfiles:/project/static
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    environment: 
      DB_USER: "${POSTGRES_USER}"
      DB_PWD: "${POSTGRES_PASSWORD}"
      DB_NAME: "${POSTGRES_DB}"
      DEBUG: "${DEBUG}"
      HEADER_AUTH: "false"
      #DB_OVERRIDE: "1"

#  worker:
#    build: .
#    restart: always
#    expose:
#      - "8000"
#    volumes:
#      - staticfiles:/project/static
#    depends_on:
#      - db
#    environment: 
#      DB_USER: "${POSTGRES_USER}"
#      DB_PWD: "${POSTGRES_PASSWORD}"
#      DB_NAME: "${POSTGRES_DB}"
#      DEBUG: "${DEBUG}"
#      #DB_OVERRIDE: "1"
#      WORKER: '1'

volumes:
  staticfiles:
  pgdata:
    external: true